# Generated by Django 5.2.1 on 2025-05-23 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for driver access', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager/Admin who approved this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hr_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hr_data',
            field=models.JSONField(blank=True, help_text='Data received from HR system', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hr_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID from HR system', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
