# Generated by Django 5.2.1 on 2025-05-23 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_approval_status_customuser_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hr_department',
            field=models.CharField(blank=True, help_text='Department from HR', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hr_designation',
            field=models.CharField(blank=True, help_text='Designation from HR', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hr_employee_type',
            field=models.CharField(blank=True, help_text='Employee type from HR', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for vehicle system access', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager/Admin who approved this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('vehicle_manager', 'Vehicle Manager'), ('driver', 'Employee (Vehicle Access)')], default='driver', max_length=20),
        ),
    ]
