# Generated by Django 5.2.1 on 2025-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
    ]
