# Generated by Django 5.2.1 on 2025-05-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='station_type',
            field=models.CharField(choices=[('fuel', 'Fuel Station'), ('charging', 'Charging Station'), ('both', 'Fuel & Charging Station')], default='fuel', max_length=20),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='charging_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Charging duration in minutes (for electric vehicles)', null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='cost_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kWh (for electric vehicles)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='energy_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Energy consumed in kWh (for electric vehicles)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='cost_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel quantity in liters (for fuel vehicles)', max_digits=6, null=True),
        ),
    ]
