# Generated by Django 5.2.1 on 2025-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='average_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average mileage in km/L', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company_owned',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_fitted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_cert_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Pollution Certificate Expiry'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purpose_of_vehicle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_valid_till',
            field=models.DateField(blank=True, null=True, verbose_name='RC Valid Till'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='usage_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('staff', 'Staff'), ('other', 'Other')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='used_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
