# Generated by Django 5.2.1 on 2025-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fix_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_capacity_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Battery capacity in kWh (for electric vehicles)', max_digits=6, null=True, verbose_name='Battery Capacity (kWh)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='charging_time_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Time to fully charge in hours', max_digits=4, null=True, verbose_name='Charging Time (hours)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='charging_type',
            field=models.CharField(blank=True, help_text='Type of charging port (Type 2, CCS, CHAdeMO, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Load capacity in KG (for commercial vehicles)', max_digits=8, null=True, verbose_name='Load Capacity (KG)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='range_per_charge',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated range per full charge in km', null=True, verbose_name='Range per Charge (km)'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal Vehicle'), ('commercial', 'Commercial Vehicle'), ('electric', 'Electric Vehicle')], default='personal', help_text='Category determines which fields are required', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='average_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average mileage in km/L (for fuel vehicles)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel tank capacity in liters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
