# Generated by Django 5.2.1 on 2025-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='Not specified', help_text='Destination location/address', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='Not specified', help_text='Starting location/address', max_length=255),
        ),
    ]
