# Generated by Django 5.2.1 on 2025-05-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_destination_trip_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Destination location/address', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(help_text='Starting location/address', max_length=255),
        ),
    ]
