# Generated by Django 5.2.1 on 2025-05-27 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_destination_alter_trip_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_locations', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['trip', 'timestamp'], name='trips_tripl_trip_id_25e17b_idx')],
            },
        ),
    ]
