# Generated by Django 5.2.1 on 2025-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_triplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripLocation',
        ),
    ]
